# Generated by Django 5.0.2 on 2024-06-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resetpasswordtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='continentCode',
            new_name='continent_code',
        ),
        migrations.RenameField(
            model_name='usercuisine',
            old_name='cuisine_id',
            new_name='cuisine',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
