# Generated by Django 5.0.2 on 2024-06-22 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_continentcode_countries_continent_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='country',
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuisine_country', to='api.countries')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cuisine_added_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='cuisine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='cuisine', to='api.cuisine'),
            preserve_default=False,
        ),
    ]
