# Generated by Django 5.0.2 on 2024-06-22 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_dishes_country_cuisine_dishes_cuisine'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercuisine',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='token_uses_ref', to='api.usertoken'),
            preserve_default=False,
        ),
    ]
