# Generated by Django 5.0.2 on 2024-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='dishimages',
            name='image',
            field=models.ImageField(upload_to='static/dish_images'),
        ),
    ]
