# Generated by Django 5.0.2 on 2024-06-27 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_countries_phone_alter_customuser_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='api.countries'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
