# Generated by Django 5.0.2 on 2024-06-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('successful', 'Successful'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='created', max_length=20),
        ),
    ]
