# Generated by Django 5.0.2 on 2024-06-28 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='payment_ref', to='api.payment'),
        ),
    ]
