# Generated by Django 5.0.2 on 2024-06-29 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_usertoken_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('local', 'Local')], default='local', max_length=50),
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_provider', models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('local', 'Local')], default='local', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
