# Generated by Django 5.0.2 on 2024-07-03 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_customuser_login_provider_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercuisine',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='cuisineitems',
            unique_together={('cuisine', 'dish')},
        ),
        migrations.CreateModel(
            name='MenuGroupUserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_for_menu', to='api.usercuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItemsDeleteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('add_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dish_add_by_user', to=settings.AUTH_USER_MODEL)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='belong_to_deleted_menu', to='api.usercuisine')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='deleted_dish', to='api.dishes')),
                ('remove_by_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dish_remove_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
