# Generated by Django 5.0.2 on 2024-07-05 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_usercuisine_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroupLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(blank=True, null=True)),
                ('leaving_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaved_menu', to='api.usercuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leaved_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MenuGroupLeaveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(blank=True, null=True)),
                ('history_created_at', models.DateTimeField(auto_now_add=True)),
                ('leaving_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaved_history_menu', to='api.usercuisine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leaved_by_user_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
