# Generated by Django 5.0.2 on 2024-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_menugroupleave_menugroupleavehistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuisineitems',
            unique_together={('cuisine', 'dish', 'user')},
        ),
    ]
