# Generated by Django 5.0.2 on 2024-07-13 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_cities_caterers_states_cities_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caterers',
            old_name='namer',
            new_name='name',
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_file', models.FileField(upload_to='static/email_pdfs/')),
                ('email_body', models.CharField(max_length=255)),
                ('email_prefix', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email_send', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('cater', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='email_to_cater', to='api.caterers')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='email_menu_to_cater', to='api.usercuisine')),
            ],
        ),
    ]
