# Generated by Django 5.0.2 on 2024-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_namer_caterers_name_dataentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='menu_file',
            field=models.FileField(upload_to='email_pdfs/'),
        ),
        migrations.AlterField(
            model_name='dishimages',
            name='image',
            field=models.ImageField(upload_to='dish_images'),
        ),
    ]
