# Generated by Django 5.0.2 on 2024-10-01 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_dataentry_menu_file_alter_dishimages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercuisine',
            name='meal_time',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='user_cuisine_meal_time', to='api.mealtimes'),
            preserve_default=False,
        ),
    ]
