# Generated by Django 5.0.2 on 2025-02-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_usercuisine_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='login_provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('local', 'Local'), ('guest', 'Guest')], default='local', max_length=50),
        ),
        migrations.AlterField(
            model_name='userloginhistory',
            name='login_provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('google', 'Google'), ('local', 'Local'), ('guest', 'Guest')], default='local', max_length=50),
        ),
    ]
